<?php

/**
 * Generates a sitemap.org compatible XML file, for use with Google and other search engines.
 *
 * Renders the sitemap if a gallery page is called with "?sitemap" in the URL.
 *
 * @author Jeppe Toustrup (Tenzer)
 * @version 2.0.0
 * @package plugins
 */

$plugin_description = 'Here goes some description about zenphoto-sitemap';
$plugin_author = 'Jeppe Toustrup (Tenzer)';
$plugin_version = '2.0.0';
$plugin_URL = 'http://tenzer.dk/open-source/zenphoto-sitemap';

// Check if '?sitemap' is specified. If it isn't then we should stop execution of this script.
if(!isset($_GET['sitemap'])) {
	return;
}

/**
 * Simple helper function which simply outputs a string and ends it of with a new-line.
 * @param  $string String
 * @return void
 */
function echonl($string) {
	echo($string . "\n");
}

/**
 * A simple wrapper function for urlencode, which allows us to use it with array_walk().
 * @param  $value The array value from array_walk()
 * @param  $key The array key from array_walk() - Not used
 * @return void
 */
function urlencodeWrapper(&$value, $key) {
	$value = urlencode($value);
}

// Output content type and charset
header('Content-Type: text/xml;charset=utf-8');

// Output XML file headers, and plug the plugin :)
echonl('<?xml version="1.0" encoding="UTF-8"?>');
echonl('<!-- Sitemap generated by zenphoto-sitemap: http://tenzer.dk/open-source/zenphoto-sitemap -->');
echonl('<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">');



// End off the <urlset> tag
echonl('</urlset>');

// Stop execution of the rest of Zenphoto
exit();