<?php

/**
 * Generates a sitemap.org compatible XML file, for use with Google and other search engines.
 *
 * Renders the sitemap if a gallery page is called with "?sitemap" in the URL.
 *
 * @author Jeppe Toustrup (Tenzer)
 * @version 2.0.0
 * @package plugins
 */

$plugin_description = 'Generates a sitemaps.org compatible XML file, for use with Google and other search engines.';
$plugin_author = 'Jeppe Toustrup (Tenzer), extended by Malte Müller (acrylian)';
$plugin_version = '2.0.0';
$plugin_URL = 'http://tenzer.dk/open-source/zenphoto-sitemap';

// Check if '?sitemap' is specified. If it isn't then we should stop execution of this script.
if(!isset($_GET['sitemap'])) {
	return;
}

/**
 * Simple helper function which simply outputs a string and ends it of with a new-line.
 * @param  $string String
 * @return void
 */
function echonl($string) {
	echo($string . "\n");
}

/**
 * A simple wrapper function for urlencode, which allows us to use it with array_walk().
 * @param  $value The array value from array_walk()
 * @param  $key The array key from array_walk() - Not used
 * @return void
 */
function urlencodeWrapper(&$value, $key) {
	$value = urlencode($value);
}

// Are we using mod_rewrite? If so, we set $mod_rewrite to the image suffix
if(1 == getOption('mod_rewrite')) {
	$mod_rewrite = urlencode(getOption('mod_rewrite_image_suffix'));
}

// Output content type and charset
header('Content-Type: text/xml;charset=utf-8');

// Output XML file headers, and plug the plugin :)
echonl('<?xml version="1.0" encoding="UTF-8"?>');
echonl('<!-- Sitemap generated by zenphoto-sitemap: http://tenzer.dk/open-source/zenphoto-sitemap -->');
echonl('<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">');

// Create an array, which all the URLs for gallery pages are going to be insert into
$urls = array();

// Add the front page of the gallery to the URL list
$urls[] = null;

// Find public albums
$public_albums = query_full_array('SELECT `id`, `folder` FROM ' . prefix('albums') . ' WHERE `show` = 1 AND `password` = "";');
foreach($public_albums as $public_album) {
	// Split up the folder path, urlencode it in single pieces, and assemble it all again
	$folder_path = explode('/', $public_album['folder']);
	array_walk($folder_path, 'urlencodeWrapper');
	$public_album['folder'] = implode('/', $folder_path);

	// Add the album to the URL list
	if($mod_rewrite) {
		$urls[] = $public_album['folder'];
	} else {
		$urls[] = '?album=' . $public_album['folder'];
	}

	// Loop over each album, and find all public images belonging to that album
	$public_images = query_full_array('SELECT `filename` FROM ' . prefix('images') . ' WHERE `albumid` = ' . $public_album['id'] . ' AND `show` = 1;');
	// Add the correct URLs to the URL list
	if($mod_rewrite) {
		foreach($public_images as $public_image) {
			$urls[] = $public_album['folder'] . '/' . urlencode($public_image['filename']) . $mod_rewrite;
		}
	} else {
		foreach($public_images as $public_image) {
			$urls[] = '?album=' . $public_album['folder'] . '&amp;image=' . urlencode($public_image['filename']);
		}
	}
}

// Zenpage optional stuff
if(getOption('zp_plugin_zenpage')) {
	// Zenpage pages
	$public_pages = query_full_array('SELECT `titlelink` FROM ' . prefix('zenpage_pages') . ' WHERE `show` = 1;');
	// Add the correct URLs to the URL list
	if($mod_rewrite) {
		foreach($public_pages as $public_page) {
			$urls[] = 'pages/' . urlencode($public_page['titlelink']);
		}
	} else {
		foreach($public_pages as $public_page) {
			$urls[] = '?p=pages&amp;title=' . urlencode($public_page['titlelink']);
		}
	}

	// Zenpage news articles
	$public_news = query_full_array('SELECT `titlelink` FROM ' . prefix('zenpage_news') . ' WHERE `show` = 1;');
	// Add the correct URLs to the URL list
	if($mod_rewrite) {
		foreach($public_news as $public_article) {
			$urls[] = 'news/' . urlencode($public_article['titlelink']);
		}
	} else {
		foreach($public_news as $public_article) {
			$urls[] = '?p=news&amp;title=' . urlencode($public_article['titlelink']);
		}
	}

	// Zenpage news categories
	$public_cats = query_full_array('SELECT `cat_link` FROM ' . prefix('zenpage_news_categories') . ';');
	// Add the correct URLs to the URL list
	if($mod_rewrite) {
		foreach($public_cats as $public_cat) {
			$urls[] = 'news/category/' . urlencode($public_cat['cat_link']);
		}
	} else {
		foreach($public_cats as $public_cat) {
			$urls[] = '?p=news&amp;category=' . urlencode($public_cat['cat_link']);
		}
	}
}

// Print out all of the URLs collected
foreach($urls as $url) {
	echonl("\t<url><loc>" . FULLWEBPATH . "/$url</loc></url>");
}

// End off the <urlset> tag
echonl('</urlset>');

// Stop execution of the rest of Zenphoto
exit();